### ISSUE TITLE
Suggestion for Yorha Visor

### ISSUE THREAD

**Issue by ArcaneTxsa** [khouryj/Thunder-Plug-in-Chips-Mod-Project#1]
I got the Yorha visor in stage 1, used it on the boss for an easy fight. The spikes on the teleporter are blocking me from getting close enough to activate it and move on, but having completed it there's not enough enemies spawning to stand a chance at putting me to critical health.

As you cannot overwrite a capture, would it be possible to make the item put you to critical health to cancel the transformation if you are already transformed? This would prevent getting stuck as a creature, and would make it easier/safer to swap transformation if your current one wasnt working out.

Thanks for reading :)

**Comment by khouryj** [comment]
I actually meant to have this as a feature but totally forgot to implement it! Currently working on removing the R2API dependency and another project but this should be out in the near future. Thank you for the feedback.

**Comment by ArcaneTxsa** [comment]
No problem, love the mod btw <3

**Comment by khouryj** [comment]
This should be fixed now, sorry for the wait. Update rolling out shortly.
